import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "@/lib/supabase";

const API_BASE = process.env.EXPO_PUBLIC_BACKEND_URL || process.env.EXPO_PUBLIC_API_URL || "https://artboost-ai.onrender.com";
type Mode = "collections" | "seo" | "inventory";
type Product = any;

export default function StoreCatalogTool({ mode }: { mode: Mode }) {
  const params = useLocalSearchParams<{storeId?:string;storeName?:string;storeType?:string}>();
  const storeId=String(params.storeId||""); const storeName=String(params.storeName||"Connected Store");
  const [products,setProducts]=useState<Product[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState("");
  const load=useCallback(async()=>{ try { setError(""); const {data:{session},error:e}=await supabase.auth.getSession(); if(e) throw e; if(!session?.access_token) throw new Error("Please sign in to ArtBoost again."); const q=new URLSearchParams({storeId,limit:"500",_ : String(Date.now())}); const r=await fetch(`${API_BASE}/products?${q.toString()}`,{headers:{Authorization:`Bearer ${session.access_token}`,"Cache-Control":"no-cache"}}); const d=await r.json(); if(!r.ok||!d.success) throw new Error(d.details||d.error||"Unable to load store products."); setProducts(Array.isArray(d.products)?d.products:[]); } catch(e:any){setError(e?.message||"Unable to load store products.");} finally {setLoading(false);setRefreshing(false);} },[storeId]);
  useEffect(()=>{load()},[load]);
  const title=mode==="collections"?"Collections":mode==="seo"?"SEO Tools":"Inventory";
  const groups=useMemo(()=>{const m=new Map<string,Product[]>(); for(const p of products){const cats=Array.isArray(p.categories)&&p.categories.length?p.categories:["Uncategorized"]; for(const c of cats){const k=String(c||"Uncategorized");m.set(k,[...(m.get(k)||[]),p]);}} return [...m.entries()].sort((a,b)=>b[1].length-a[1].length)},[products]);
  const seoScore=(p:Product)=>{let n=0;if(String(p.title||"").trim().length>=20)n++;if(String(p.description||"").trim().length>=80)n++;if(Array.isArray(p.tags)&&p.tags.length>=3)n++;if(p.image_url)n++;if(p.product_url)n++;return n;};
  if(loading) return <SafeAreaView style={s.screen}><View style={s.center}><ActivityIndicator size="large"/><Text style={s.muted}>Loading {title.toLowerCase()}…</Text></View></SafeAreaView>;
  return <SafeAreaView style={s.screen}><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={23} color="#fff"/></Pressable><View style={{flex:1}}><Text style={s.eyebrow}>{storeName.toUpperCase()}</Text><Text style={s.title}>{title}</Text></View></View><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>}>{error?<Text style={s.error}>{error}</Text>:null}{products.length===0?<Text style={s.muted}>No products are imported for this store yet.</Text>:null}
  {mode==="collections"&&groups.map(([name,items])=><View key={name} style={s.card}><Text style={s.cardTitle}>{name}</Text><Text style={s.muted}>{items.length} product{items.length===1?"":"s"}</Text>{items.slice(0,5).map(p=><Text key={p.id} style={s.row}>• {p.title||"Untitled product"}</Text>)}</View>)}
  {mode==="seo"&&products.map(p=>{const score=seoScore(p);return <Pressable key={p.id} style={s.card} onPress={()=>router.push({pathname:"/product-details" as any,params:{productId:p.id,storeId}})}><View style={s.line}><Text style={[s.cardTitle,{flex:1}]} numberOfLines={2}>{p.title||"Untitled product"}</Text><Text style={s.score}>{score}/5</Text></View><Text style={s.muted}>{score===5?"SEO essentials complete":"Needs: "+[String(p.title||"").trim().length<20?"stronger title":"",String(p.description||"").trim().length<80?"description":"",!(Array.isArray(p.tags)&&p.tags.length>=3)?"keywords/tags":"",!p.image_url?"image":"",!p.product_url?"listing link":""].filter(Boolean).join(", ")}</Text></Pressable>})}
  {mode==="inventory"&&products.map(p=><Pressable key={p.id} style={s.card} onPress={()=>router.push({pathname:"/product-details" as any,params:{productId:p.id,storeId}})}><View style={s.line}><Text style={[s.cardTitle,{flex:1}]} numberOfLines={2}>{p.title||"Untitled product"}</Text><Text style={s.status}>{String(p.status||"unknown").toUpperCase()}</Text></View><Text style={s.muted}>Quantity: {p?.metadata?.inventoryQuantity ?? "Not reported"}  •  Last sync: {p.last_synced_at?new Date(p.last_synced_at).toLocaleString():"Not available"}</Text></Pressable>)}
  </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#0b0b0b"},center:{flex:1,alignItems:"center",justifyContent:"center",gap:12},header:{flexDirection:"row",alignItems:"center",gap:14,padding:18,borderBottomWidth:1,borderBottomColor:"#222"},back:{width:44,height:44,borderRadius:14,backgroundColor:"#171717",alignItems:"center",justifyContent:"center"},eyebrow:{fontSize:10,fontWeight:"900",letterSpacing:1.2,color:"#8b5cf6"},title:{fontSize:24,fontWeight:"900",color:"#fff"},content:{padding:18,paddingBottom:48,gap:12},card:{padding:16,borderRadius:18,backgroundColor:"#151515",borderWidth:1,borderColor:"#2a2a2a"},cardTitle:{fontSize:16,fontWeight:"800",color:"#fff"},muted:{color:"#a1a1aa",marginTop:5},row:{color:"#ddd",marginTop:8},line:{flexDirection:"row",alignItems:"center",gap:12},score:{color:"#c4b5fd",fontSize:18,fontWeight:"900"},status:{color:"#c4b5fd",fontWeight:"900"},error:{color:"#fca5a5",marginBottom:8}});
