import { buildStorePublishingActivityAnswer, __test } from "../services/consultantPublishingActivity.js";
const assert=(v,m)=>{if(!v)throw new Error(m)};
const now=new Date("2026-09-15T18:30:00.000Z");
const base={authenticated:true,connectedStores:[{id:"s1",name:"Shopify"}],activeAutomations:[{timezone:"America/Chicago"}],contextSources:{automationLogsMatchMethod:"user_id"}};
assert(__test.isPublishingActivityQuestion("Were all my scheduled posts successful today?"),"intent");
assert(__test.isPublishingActivityQuestion("How many posts were successful today?"),"time-scoped count intent without scheduled/store wording");
const ok={...base,automationLogs:[{store_id:"s1",event_type:"post_success",status:"success",platforms:["facebook","instagram"],publish_result:{results:[{platform:"facebook",success:true},{platform:"instagram",success:true}]},created_at:"2026-09-15T15:00:00.000Z"}]};
const yes=buildStorePublishingActivityAnswer("Were all my scheduled posts successful today?",ok,{now});
assert(yes?.answer?.startsWith("Yes."),"yes");
const count=buildStorePublishingActivityAnswer("How many posts were successful today?",ok,{now});
assert(count?.answer?.startsWith("2 scheduled platform posts were successfully published today."),"direct today count");
assert(!/611|606|all recorded history|lifetime/i.test(count.answer),"must not use lifetime totals");
const mixed={...base,automationLogs:[{store_id:"s1",event_type:"post_success",status:"success",platforms:["facebook","instagram","threads","pinterest"],publish_result:{results:[{platform:"facebook",success:true},{platform:"instagram",success:false,error:"provider rejected media"},{platform:"threads",skipped:true,status:"skipped"}]},created_at:"2026-09-15T15:00:00.000Z"}]};
const no=buildStorePublishingActivityAnswer("Were all my scheduled posts successful today?",mixed,{now});
assert(no?.answer?.startsWith("No."),"no");
assert(no.answer.includes("1 failed")&&no.answer.includes("1 skipped")&&no.answer.includes("1 unverified"),"outcomes");
const old={...base,automationLogs:[{store_id:"s1",event_type:"post_success",status:"success",platforms:["facebook"],publish_result:{results:[{platform:"facebook",success:true}]},created_at:"2026-09-14T15:00:00.000Z"}]};
const empty=buildStorePublishingActivityAnswer("Were all my scheduled posts successful today?",old,{now});
assert(empty?.confidence==="unknown","today boundary");
console.log("PASS: exact scheduled-post question");
console.log("PASS: time-scoped count routes without scheduled/store wording");
console.log("PASS: direct successful-post count; no lifetime fallback");
console.log("PASS: America/Chicago today boundary");
console.log("PASS: success/failure/skipped/unverified reconciliation");
console.log("PASS: no yesterday/lifetime fallback");
