const SESSION_KEY="artboost_web_session";const raw=localStorage.getItem(SESSION_KEY);let session;try{session=JSON.parse(raw||"null")}catch{}if(!session?.access_token||!session?.user?.id){location.replace("/");}
let authConfigPromise=null,refreshPromise=null;
async function authConfig(){if(!authConfigPromise)authConfigPromise=fetch("/api/public-auth-config",{headers:{Accept:"application/json"}}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok||!d.supabaseUrl||!(d.supabasePublishableKey||d.supabaseAnonKey))throw new Error("Web authentication configuration is unavailable.");return {url:String(d.supabaseUrl).replace(/\/$/,""),key:d.supabasePublishableKey||d.supabaseAnonKey}});return authConfigPromise}
function saveSession(next){session=next;localStorage.setItem(SESSION_KEY,JSON.stringify(next))}
function clearSession(){localStorage.removeItem(SESSION_KEY);location.replace("/")}
async function refreshSession(force=false){if(!session?.refresh_token)throw new Error("Session cannot be refreshed.");if(!force&&session.expires_at&&Number(session.expires_at)>Date.now()+60000)return session;if(refreshPromise)return refreshPromise;refreshPromise=(async()=>{const cfg=await authConfig();const r=await fetch(cfg.url+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{apikey:cfg.key,Authorization:"Bearer "+cfg.key,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refresh_token})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(d.error_description||d.msg||"Session refresh failed.");const expiresIn=Number(d.expires_in||3600);saveSession({...session,...d,refresh_token:d.refresh_token||session.refresh_token,expires_in:expiresIn,expires_at:Date.now()+expiresIn*1000,user:d.user||session.user});return session})().finally(()=>{refreshPromise=null});return refreshPromise}
const auth=()=>({Authorization:"Bearer "+session.access_token,Accept:"application/json"});const status=document.querySelector("#status");document.querySelector("#accountEmail").textContent=session?.user?.email||"";document.querySelector("#welcome").textContent=session?.user?.user_metadata?.full_name?"Welcome back, "+session.user.user_metadata.full_name:"Welcome back";document.querySelector("#signOut").onclick=()=>clearSession();async function api(path,options={}){try{await refreshSession(false)}catch{clearSession();throw new Error("Session expired")}const request=()=>fetch(path,{...options,headers:{...auth(),...(options.headers||{})}});let r=await request();if(r.status===401){try{await refreshSession(true);r=await request()}catch{clearSession();throw new Error("Session expired")}}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.details||"Request failed");return d}function safeHttpUrl(value){try{const u=new URL(String(value||""),location.origin);return (u.protocol==="https:"||u.protocol==="http:")?u.href:""}catch{return ""}}function productCard(p){const image=safeHttpUrl(p.imageUrl||p.image_url||p.image||p.thumbnailUrl||p.thumbnail_url||"");const title=p.title||p.name||"Untitled product";const store=p.storeName||p.store_name||p.storeType||p.store_type||"";return '<article class="product">'+(image?'<img src="'+escapeHtml(image)+'" alt="">':'')+'<div><h3>'+escapeHtml(title)+'</h3><p>'+escapeHtml(store)+'</p></div></article>'}function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}async function load(){status.className="status";status.textContent="Loading your ArtBoost data…";try{const [p,s]=await Promise.all([api("/products?limit=60"),api("/stores")]);const products=p.products||p.items||[];const stores=s.stores||[];document.querySelector("#productCount").textContent=p.total??products.length;document.querySelector("#storeCount").textContent=s.total??stores.filter(x=>x.connected!==false).length;document.querySelector("#accountState").textContent="Connected";document.querySelector("#products").innerHTML=products.length?products.map(productCard).join(""):'<div class="empty">No products found yet.</div>';status.textContent="Your ArtBoost account is connected to the web workspace."}catch(e){status.className="status error";status.textContent=e.message||"Unable to load workspace.";document.querySelector("#accountState").textContent="Error"}}const viewContent=document.querySelector("#viewContent"),panelTitle=document.querySelector("#panelTitle"),panelEyebrow=document.querySelector("#panelEyebrow");
async function showView(view){
 document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===view));
 if(view==="home"){panelEyebrow.textContent="COMMAND CENTER";panelTitle.textContent="Dashboard";viewContent.innerHTML='<div id="dashboardContent" class="dashboardGrid"><article class="dashboardBlock"><span>CATALOG</span><h3>Your Products</h3><p>Review the artwork and products available to ArtBoost for campaigns and marketing.</p><button class="secondary-btn dashboardAction" data-dashboard-view="products">Open Products</button></article><article class="dashboardBlock"><span>COMMERCE</span><h3>Connected Stores</h3><p>Review the stores currently connected to your ArtBoost account.</p><button class="secondary-btn dashboardAction" data-dashboard-view="stores">Open Stores</button></article><article class="dashboardBlock"><span>AI MARKETING AGENT</span><h3>AI Consultant</h3><p>Ask ArtBoost about your products, stores, publishing activity, and marketing strategy.</p><button class="secondary-btn dashboardAction" data-dashboard-view="consultant">Ask Consultant</button></article><article class="dashboardBlock"><span>CREATE & PUBLISH</span><h3>Create Content</h3><p>Generate platform-ready marketing content from your artwork and product links.</p><button class="secondary-btn dashboardAction" data-dashboard-view="create">Create Content</button></article><article class="dashboardBlock"><span>AUTOMATION</span><h3>Schedules</h3><p>Review active and disabled scheduled automations from one workspace.</p><button class="secondary-btn dashboardAction" data-dashboard-view="schedule">Open Schedule</button></article><article class="dashboardBlock"><span>SOCIAL</span><h3>Connections</h3><p>Check the connection state of supported social publishing platforms.</p><button class="secondary-btn dashboardAction" data-dashboard-view="connections">Open Connections</button></article></div>';document.querySelectorAll("[data-dashboard-view]").forEach(b=>b.onclick=()=>showView(b.dataset.dashboardView));status.className="status";status.textContent="Your ArtBoost command center is ready.";return}
 if(view==="products"){panelEyebrow.textContent="YOUR CATALOG";panelTitle.textContent="Products";viewContent.innerHTML='<div id="products" class="products"></div>';await load();return}
 status.className="status";status.textContent="Loading "+view+"…";
 try{
  if(view==="stores"){const d=await api("/stores");panelEyebrow.textContent="CONNECTED COMMERCE";panelTitle.textContent="Stores";viewContent.innerHTML=(d.stores||[]).map(x=>'<article class="product"><div><h3>'+escapeHtml(x.name||x.store_name||x.platform||x.store_type||"Store")+'</h3><p>'+escapeHtml(x.connected===false?"Disconnected":"Connected")+'</p></div></article>').join("")||'<div class="empty">No stores connected.</div>';status.textContent="Store connections loaded.";return}
  if(view==="schedule"){const d=await api("/automations");panelEyebrow.textContent="AUTOMATION";panelTitle.textContent="Scheduled Automations";viewContent.innerHTML=(d.automations||[]).map(x=>'<article class="product"><div><h3>'+escapeHtml(x.name||x.store_name||x.store_type||"Store automation")+'</h3><p>'+escapeHtml(x.enabled===false?"Disabled":"Active")+'</p></div></article>').join("")||'<div class="empty">No scheduled automations found.</div>';status.textContent="Scheduled automations loaded.";return}
  if(view==="connections"){const d=await api("/social-connect/providers");panelEyebrow.textContent="SOCIAL";panelTitle.textContent="Social Connections";const providers=d.providers||[];const states=await Promise.all(providers.map(async p=>{try{return [p,await api("/social-connect/status/"+encodeURIComponent(p.id))]}catch{return [p,{connected:false}]}}));viewContent.innerHTML=states.map(([p,s])=>'<article class="product"><div><h3>'+escapeHtml(p.name||p.label||p.id)+'</h3><p>'+escapeHtml(s.connected===true?"Connected":s.connected===null?"Managed by platform":"Not connected")+'</p></div></article>').join("");status.textContent="Social connection status loaded.";return}
  if(view==="consultant"){panelEyebrow.textContent="AI MARKETING AGENT";panelTitle.textContent="AI Consultant";viewContent.innerHTML='<div class="consultant"><div id="consultantMessages" class="consultantMessages"><div class="assistantBubble">Ask me about your ArtBoost products, stores, publishing activity, marketing strategy, or what to create next.</div></div><form id="consultantForm" class="consultantForm"><textarea id="consultantQuestion" maxlength="1200" placeholder="Ask your AI Consultant…" required></textarea><button class="goldAction" type="submit">Ask Consultant</button></form></div>';document.querySelector("#consultantForm").onsubmit=askConsultant;status.textContent="AI Consultant is connected to your authenticated ArtBoost account.";return}
  if(view==="create"){panelEyebrow.textContent="CREATE";panelTitle.textContent="AI Content";viewContent.innerHTML='<form id="createForm" class="createForm"><label>Artwork image<input id="artworkFile" type="file" accept="image/*" required></label><label>Platform<select id="createPlatform"><option>Pinterest</option><option>Facebook</option><option>Instagram</option><option>X</option></select></label><label>Style<select id="createStyle"><option>Professional</option><option>Bold</option><option>Friendly</option><option>Minimal</option></select></label><label>Product link<input id="productLink" type="url" placeholder="https://…"></label><button class="goldAction" type="submit">Generate Content</button></form><div id="createResult" class="createResult"></div>';document.querySelector("#createForm").onsubmit=generateContent;status.textContent="Upload artwork and generate platform-ready marketing content.";return}
 }catch(e){status.className="status error";status.textContent=e.message||"Unable to load this workspace view."}
}
function parseGeneratedContent(text){const raw=String(text||"");const read=(name,next)=>{const start=raw.indexOf(name+":");if(start<0)return "";const from=start+name.length+1;const end=next?raw.indexOf(next+":",from):-1;return raw.slice(from,end>=0?end:raw.length).trim()};return {title:read("TITLE","DESCRIPTION"),description:read("DESCRIPTION","HASHTAGS"),hashtags:read("HASHTAGS","CTA"),cta:read("CTA","")}}
async function loadPinterestBoards(select){select.innerHTML='<option value="">Loading boards…</option>';try{const d=await api("/pinterest/boards");const boards=d.items||d.boards||[];select.innerHTML='<option value="">Choose a Pinterest board</option>'+boards.map(b=>'<option value="'+escapeHtml(b.id||"")+'">'+escapeHtml(b.name||"Untitled board")+'</option>').join("");if(boards.length===1)select.value=String(boards[0].id||"");if(!boards.length)select.innerHTML='<option value="">No Pinterest boards available</option>'}catch(e){select.innerHTML='<option value="">Pinterest connection required</option>';status.className="status error";status.textContent=e.message||"Unable to load Pinterest boards."}}
async function publishGeneratedPinterest(button){
  const g=window.artboostGenerated;
  if(!g||g.platform!=="Pinterest"){status.className="status error";status.textContent="Pinterest content is not ready. Generate the content again.";return}
  const board=document.querySelector("#generatedBoard");
  const boardId=board?.value;
  if(!boardId){status.className="status error";status.textContent="Choose a Pinterest board first.";board?.focus();return}
  button.disabled=true;
  button.textContent="Publishing…";
  status.className="status";
  status.textContent="Publishing to Pinterest…";
  try{
    const d=await api("/pinterest/create-pin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({boardId,title:g.title,description:[g.description,g.hashtags,g.cta].filter(Boolean).join("\n\n"),link:g.productLink,imageUrl:g.imageUrl})});
    status.className="status";
    status.textContent="Published to Pinterest successfully.";
    button.textContent="Published";
    button.dataset.published="true";
    return d;
  }catch(e){
    button.disabled=false;
    button.textContent="Publish to Pinterest";
    status.className="status error";
    status.textContent=e.message||"Pinterest publishing failed.";
  }
}
async function scheduleGeneratedPinterest(button){const g=window.artboostGenerated;if(!g||g.platform!=="Pinterest")return;const boardId=document.querySelector("#generatedBoard")?.value,publishAt=document.querySelector("#generatedPublishAt")?.value;if(!boardId){status.className="status error";status.textContent="Choose a Pinterest board first.";return}if(!publishAt){status.className="status error";status.textContent="Choose a date and time first.";return}const iso=new Date(publishAt).toISOString();if(new Date(iso).getTime()<=Date.now()){status.className="status error";status.textContent="Schedule time must be in the future.";return}button.disabled=true;button.textContent="Scheduling…";try{await api("/schedule-campaign",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:g.title||"Pinterest Campaign",description:g.description||g.raw,imageUrl:g.imageUrl,productLink:g.productLink,boardId,hashtags:g.hashtags,cta:g.cta,publishAt:iso,platform:"Pinterest",repeatType:"one_time"})});status.className="status";status.textContent="Pinterest campaign scheduled successfully.";button.textContent="Scheduled"}catch(e){button.disabled=false;button.textContent="Schedule";status.className="status error";status.textContent=e.message||"Scheduling failed."}}
async function generateContent(event){event.preventDefault();const file=document.querySelector("#artworkFile").files[0],platform=document.querySelector("#createPlatform").value,style=document.querySelector("#createStyle").value,link=document.querySelector("#productLink").value.trim(),out=document.querySelector("#createResult");if(!file)return;out.textContent="Generating…";const form=new FormData();form.append("image",file,file.name||"artwork.jpg");form.append("productLink",link);form.append("platform",platform);form.append("stylePreset",style);try{try{await refreshSession(false)}catch{clearSession();throw new Error("Session expired")}const request=()=>fetch("/generate",{method:"POST",headers:{Authorization:"Bearer "+session.access_token},body:form});let r=await request();if(r.status===401){try{await refreshSession(true);r=await request()}catch{clearSession();throw new Error("Session expired")}}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.details||"Generation failed");const generatedImage=safeHttpUrl(d.imageUrl||"");const parsed=parseGeneratedContent(d.result||"");window.artboostGenerated={platform,imageUrl:generatedImage,productLink:link,raw:d.result||"",...parsed};const pinterestActions=platform==="Pinterest"?'<div class="createActions"><label>Pinterest board<select id="generatedBoard"><option value="">Loading boards…</option></select></label><label>Schedule date/time<input id="generatedPublishAt" type="datetime-local"></label><div><button id="publishPinterest" class="goldAction" type="button">Publish to Pinterest</button> <button id="schedulePinterest" class="secondary-btn" type="button">Schedule</button></div></div>':"";out.innerHTML='<div class="generated">'+(generatedImage?'<img src="'+escapeHtml(generatedImage)+'" alt="">':'')+'<div><h3>'+escapeHtml(platform)+" Content"+'</h3><pre>'+escapeHtml(d.result||"No content returned.")+'</pre>'+pinterestActions+'</div></div>';if(platform==="Pinterest"){const board=document.querySelector("#generatedBoard");await loadPinterestBoards(board);const publishButton=document.querySelector("#publishPinterest");const scheduleButton=document.querySelector("#schedulePinterest");if(publishButton)publishButton.onclick=()=>publishGeneratedPinterest(publishButton);if(scheduleButton)scheduleButton.onclick=()=>scheduleGeneratedPinterest(scheduleButton)}status.className="status";status.textContent="AI content generated successfully."}catch(e){out.innerHTML='<div class="assistantBubble error">'+escapeHtml(e.message||"Generation failed.")+'</div>';status.className="status error";status.textContent="Content generation failed."}}
async function askConsultant(event){event.preventDefault();const input=document.querySelector("#consultantQuestion"),messages=document.querySelector("#consultantMessages"),question=input.value.trim();if(!question)return;messages.insertAdjacentHTML("beforeend",'<div class="userBubble">'+escapeHtml(question)+'</div>');input.value="";const waiting=document.createElement("div");waiting.className="assistantBubble";waiting.textContent="Thinking…";messages.appendChild(waiting);try{const d=await api("/ai/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,currentScreen:"web-workspace",appVersion:"web",assistantMode:"marketing_consultant",conversation:[]})});waiting.textContent=d.answer||d.message||"I completed the request, but no answer text was returned."}catch(e){waiting.textContent=e.message||"The AI Consultant is temporarily unavailable.";waiting.classList.add("error")}messages.scrollTop=messages.scrollHeight}
document.querySelector("#refresh").onclick=()=>showView(document.querySelector("[data-view].active")?.dataset.view||"products");
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));
load();