const raw=localStorage.getItem("artboost_web_session");let session;try{session=JSON.parse(raw||"null")}catch{}if(!session?.access_token||!session?.user?.id){location.replace("/");}const auth=()=>({Authorization:"Bearer "+session.access_token,Accept:"application/json"});const status=document.querySelector("#status");document.querySelector("#accountEmail").textContent=session?.user?.email||"";document.querySelector("#welcome").textContent=session?.user?.user_metadata?.full_name?"Welcome back, "+session.user.user_metadata.full_name:"Welcome back";document.querySelector("#signOut").onclick=()=>{localStorage.removeItem("artboost_web_session");location.replace("/")};async function api(path){const r=await fetch(path,{headers:auth()});const d=await r.json().catch(()=>({}));if(r.status===401){localStorage.removeItem("artboost_web_session");location.replace("/");throw new Error("Session expired")}if(!r.ok)throw new Error(d.error||d.details||"Request failed");return d}function productCard(p){const image=p.imageUrl||p.image_url||p.image||p.thumbnailUrl||p.thumbnail_url||"";const title=p.title||p.name||"Untitled product";const store=p.storeName||p.store_name||p.storeType||p.store_type||"";return '<article class="product">'+(image?'<img src="'+String(image).replace(/"/g,"&quot;")+'" alt="">':'')+'<div><h3>'+escapeHtml(title)+'</h3><p>'+escapeHtml(store)+'</p></div></article>'}function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}async function load(){status.className="status";status.textContent="Loading your ArtBoost data…";try{const [p,s]=await Promise.all([api("/products?limit=60"),api("/stores")]);const products=p.products||p.items||[];const stores=s.stores||[];document.querySelector("#productCount").textContent=p.total??products.length;document.querySelector("#storeCount").textContent=s.total??stores.filter(x=>x.connected!==false).length;document.querySelector("#accountState").textContent="Connected";document.querySelector("#products").innerHTML=products.length?products.map(productCard).join(""):'<div class="empty">No products found yet.</div>';status.textContent="Your ArtBoost account is connected to the web workspace."}catch(e){status.className="status error";status.textContent=e.message||"Unable to load workspace.";document.querySelector("#accountState").textContent="Error"}}const viewContent=document.querySelector("#viewContent"),panelTitle=document.querySelector("#panelTitle"),panelEyebrow=document.querySelector("#panelEyebrow");
async function showView(view){
 document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===view));
 if(view==="home"||view==="products"){panelEyebrow.textContent="YOUR CATALOG";panelTitle.textContent="Products";viewContent.innerHTML='<div id="products" class="products"></div>';await load();return}
 status.className="status";status.textContent="Loading "+view+"…";
 try{
  if(view==="stores"){const d=await api("/stores");panelEyebrow.textContent="CONNECTED COMMERCE";panelTitle.textContent="Stores";viewContent.innerHTML=(d.stores||[]).map(x=>'<article class="product"><div><h3>'+escapeHtml(x.name||x.store_name||x.platform||x.store_type||"Store")+'</h3><p>'+escapeHtml(x.connected===false?"Disconnected":"Connected")+'</p></div></article>').join("")||'<div class="empty">No stores connected.</div>';status.textContent="Store connections loaded.";return}
  if(view==="schedule"){const d=await api("/automations");panelEyebrow.textContent="AUTOMATION";panelTitle.textContent="Scheduled Automations";viewContent.innerHTML=(d.automations||[]).map(x=>'<article class="product"><div><h3>'+escapeHtml(x.name||x.store_name||x.store_type||"Store automation")+'</h3><p>'+escapeHtml(x.enabled===false?"Disabled":"Active")+'</p></div></article>').join("")||'<div class="empty">No scheduled automations found.</div>';status.textContent="Scheduled automations loaded.";return}
  if(view==="connections"){const d=await api("/social-connect/providers");panelEyebrow.textContent="SOCIAL";panelTitle.textContent="Social Connections";const providers=d.providers||[];const states=await Promise.all(providers.map(async p=>{try{return [p,await api("/social-connect/status/"+encodeURIComponent(p.id))]}catch{return [p,{connected:false}]}}));viewContent.innerHTML=states.map(([p,s])=>'<article class="product"><div><h3>'+escapeHtml(p.name||p.label||p.id)+'</h3><p>'+escapeHtml(s.connected===true?"Connected":s.connected===null?"Managed by platform":"Not connected")+'</p></div></article>').join("");status.textContent="Social connection status loaded.";return}
  if(view==="create"){panelEyebrow.textContent="CREATE";panelTitle.textContent="AI Content";viewContent.innerHTML='<div class="empty">Your authenticated Create workspace is the next publishing surface being connected.</div>';status.textContent="Your ArtBoost account is ready for AI creation.";return}
 }catch(e){status.className="status error";status.textContent=e.message||"Unable to load this workspace view."}
}
document.querySelector("#refresh").onclick=()=>showView(document.querySelector("[data-view].active")?.dataset.view||"products");document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));load();